### ISSUE TITLE
AttributeError: 'Subject' object has no attribute 'voxel_to_native_matrix'

### ISSUE THREAD

**Issue by nicogravel** [WinawerLab/MRI_tools#6]
I am trying to use **to_freesurfer.py**  with the output of my own pipeline (rather than _timeseries_corrected_runXX.nii_ from **prisma_preproc.py**) to align my denoised data to freesurfer (e.g. ICA-FIX  followed by FSL _fslswapdim func_run01.nii.gz x -z y func_run01.nii.gz_ and, to obtain the tkreg.dat, I use mri_coreg, bbregister) but I get this obscure error (as suggested here https://wikis.nyu.edu/pages/viewpage.action?pageId=86054639, the tkreg.dat is not applied before submitting to to_freesurfer.py): 

python to_freesurfer.py  -s -o /Volumes/HD02/Ganzfeld/S14 -v /Volumes/HD02/Ganzfeld/S14/fsurf/tkreg_run01.dat /Volumes/HD02/Ganzfeld/S14/fsurf/func_run01.nii.gz --verbose
...

**AttributeError: 'Subject' object has no attribute 'voxel_to_native_matrix'**

I have try reinstalling nypipe (as suggested here: https://wikis.nyu.edu/pages/viewpage.action?pageId=86054639), different python versions and environments and neuropythy versions, module versions, etc. Nothing seems to fix the issue on my mac (**Os 10.14 Mojave**). 

For the moment, applying tkreg.dat on the swapped denoised data func_run01.nii.gz (using mri_vol2vol) and then mri_vol2surf does it. However, it would be great to make it work! final aim is to reduce dependence on Matlab, mrVista and move to python based solutions. (e.g. neuropythy, pycortex, etc). 

I also get it using python 2.7. Big headache. Any clue??? Eager to make it work! :)

Thanks and best wishes,
Nicolas

**Comment by noahbenson** [comment]
Hi Nicolas, I think this might be an issue introduced in a neuropythy update recently that we hadn't yet caught because we've switched to mostly doing things with fMRIprep instead of the prisma_preproc/to_freesurfer way. On a hunch, if you downgrade to neuropythy 0.5.0 (which should still be available on pypi and dockerhub), this will probably work; that said, I wouldn't advise using that version of neuropythy generally--there are a lot of improvements since then. I'll take a look and see if it's a simple fix today in the meantime.

**Comment by noahbenson** [comment]
Also, if you wouldn't mind posting the full stack-trace for the error, that would be helpful!

**Comment by noahbenson** [comment]
Okay, I just pushed a change that should have fixed this; however I'm traveling so can't test it at the moment. If it seems to work now go ahead and close this issue; otherwise, let me know what has changed :-)

**Comment by nicogravel** [comment]
Great to sort this out quickly!!! The projection to surface seems to fail. Should I expect a .mgz file ? I get only a nifti file. Thanks!

(base) Nicolas-MacBook-Pro:~ nicogravel$ source neuropito/bin/activate
(neuropito) (base) Nicolas-MacBook-Pro:preprocessing nicogravel$ python to_freesurfer.py -s -o /Volumes/HD02/Ganzfeld/S14 -v /Volumes/HD02/Ganzfeld/S14/fsurf/tkreg_run01.dat /Volumes/HD02/Ganzfeld/S14/fsurf/func_run01.nii.gz --verbose
Processing EPI /Volumes/HD02/Ganzfeld/S14/fsurf/func_run01.nii.gz...
   - Correcting volume orientation...
   - Projecting to surface...
/Users/nicogravel/Documents/Python/neuropito/lib/python3.7/site-packages/pint/quantity.py:221: BehaviorChangeWarning: The way Pint handles NumPy operations has changed with the
implementation of NEP 18. Unimplemented NumPy operations will now fail instead of making
assumptions about units. Some functions, eg concat, will now return Quanties with units, where
they returned ndarrays previously. See https://github.com/hgrecco/pint/pull/905.

To hide this warning, wrap your first creation of an array Quantity with
warnings.catch_warnings(), like the following:

import numpy as np
import warnings
from pint import Quantity

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    Quantity([])

To disable the new behavior, see
https://www.numpy.org/neps/nep-0018-array-function-protocol.html#implementation

  warnings.warn(array_function_change_msg, BehaviorChangeWarning)
Traceback (most recent call last):
  File "to_freesurfer.py", line 127, in <module>
    main(sys.argv)
  File "to_freesurfer.py", line 111, in main
    method=args.method, dtype=np.float32)
  File "/Users/nicogravel/Documents/Python/neuropito/lib/python3.7/site-packages/neuropythy/mri/core.py", line 441, in image_to_cortex
    for h in ['lh', 'rh']])
  File "/Users/nicogravel/Documents/Python/neuropito/lib/python3.7/site-packages/neuropythy/mri/core.py", line 441, in <listcomp>
    for h in ['lh', 'rh']])
  File "/Users/nicogravel/Documents/Python/neuropito/lib/python3.7/site-packages/neuropythy/mri/core.py", line 445, in image_to_cortex
    method=method, fill=fill, dtype=dtype, weights=weights)
  File "/Users/nicogravel/Documents/Python/neuropito/lib/python3.7/site-packages/neuropythy/mri/core.py", line 650, in from_image
    weights=weights)
  File "/Users/nicogravel/Documents/Python/neuropito/lib/python3.7/site-packages/neuropythy/geometry/mesh.py", line 1962, in from_image
    return image_interpolate(image, xyz, method=method, fill=fill, dtype=dtype, weights=weights)
  File "/Users/nicogravel/Documents/Python/neuropito/lib/python3.7/site-packages/neuropythy/mri/images.py", line 782, in image_interpolate
    imsh = np.reshape(image.shape, (3,1))
  File "<__array_function__ internals>", line 6, in reshape
  File "/Users/nicogravel/Documents/Python/neuropito/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/nicogravel/Documents/Python/neuropito/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/nicogravel/Documents/Python/neuropito/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 4 into shape (3,1)

**Comment by nicogravel** [comment]
That happens with a 4D nifti: it fails at line 110. With a 3D nifti (e.g. Tmean) it get pass line 110, but then fails at line 122: 

Traceback (most recent call last):
  File "/Users/nicogravel/Documents/fMRI/MRI_tools-master/preprocessing/to_freesurfer.py", line 128, in <module>
    main(sys.argv)
  File "/Users/nicogravel/Documents/fMRI/MRI_tools-master/preprocessing/to_freesurfer.py", line 122, in main
    np.transpose(reduce(np.expand_dims, [-1,-1], d), (0,2,3,1)),
  File "/Users/nicogravel/opt/anaconda3/envs/neuropoto/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 639, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/Users/nicogravel/opt/anaconda3/envs/neuropoto/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)

(btw: no warning message using python 2.7)

**Comment by noahbenson** [comment]
Okay, I just took a quick look at this. First, I don't think the script was ever supposed to work with 3D images, so I would expect those to fail. For the 4D case, I think I have traced it to a bug in a recently updated function in neuropythy, but I again I have limited ability to test it right now.  I went ahead and pushed the changes to github, but I don't really want to push them to pypi before I test them more fully, so if you want to try this now, you'll need to pull neuropythy from github then install it manually. This should look like this:

```bash
> git clone https://github.com/noahbenson/neuropythy
> cd neuropythy
> python setup.py install
```
Or, I'll be back in NYC on Friday and can do more tests then if you want to wait!

**Comment by nicogravel** [comment]
was trying with 3D just for debugging purposes. This is what I get now:

Traceback (most recent call last):
  File "/Users/nicogravel/Documents/fMRI/MRI_tools-master/preprocessing/to_freesurfer.py", line 128, in <module>
    main(sys.argv)
  File "/Users/nicogravel/Documents/fMRI/MRI_tools-master/preprocessing/to_freesurfer.py", line 111, in main
    method=args.method, dtype=np.float32)
  File "/Users/nicogravel/Documents/Python/neurofito/lib/python3.7/site-packages/neuropythy-0.11.0-py3.7.egg/neuropythy/mri/core.py", line 441, in image_to_cortex
    for h in ['lh', 'rh']])
  File "/Users/nicogravel/Documents/Python/neurofito/lib/python3.7/site-packages/neuropythy-0.11.0-py3.7.egg/neuropythy/mri/core.py", line 441, in <listcomp>
    for h in ['lh', 'rh']])
  File "/Users/nicogravel/Documents/Python/neurofito/lib/python3.7/site-packages/neuropythy-0.11.0-py3.7.egg/neuropythy/mri/core.py", line 445, in image_to_cortex
    method=method, fill=fill, dtype=dtype, weights=weights)
  File "/Users/nicogravel/Documents/Python/neurofito/lib/python3.7/site-packages/neuropythy-0.11.0-py3.7.egg/neuropythy/mri/core.py", line 650, in from_image
    weights=weights)
  File "/Users/nicogravel/Documents/Python/neurofito/lib/python3.7/site-packages/neuropythy-0.11.0-py3.7.egg/neuropythy/geometry/mesh.py", line 1962, in from_image
    return image_interpolate(image, xyz, method=method, fill=fill, dtype=dtype, weights=weights)
  File "/Users/nicogravel/Documents/Python/neurofito/lib/python3.7/site-packages/neuropythy-0.11.0-py3.7.egg/neuropythy/mri/images.py", line 814, in image_interpolate
    res[ok] = np.sum(wgts * vals, axis=0)[ok2]
ValueError: operands could not be broadcast together with shapes (8,160226) (8,160226,205)
